//
//  AreaCodeJSON.swift
//  AreaCodeChecker
//
//  Created by Tayler Moosa on 2/22/20.
//  Copyright © 2020 Tayler Moosa. All rights reserved.
//

import Foundation

let areaCodeData = [
    ["201", "EST", "New Jersey", "US"],
    ["202", "EST", "District of Columbia", "US"],
    ["203", "EST", "Connecticut", "US"],
    ["204", "CST", "Manitoba", "CA"],
    ["205", "CST", "Alabama", "US"],
    ["206", "PST", "Washington", "US"],
    ["207", "EST", "Maine", "US"],
    ["208", "*MST, PST", "Idaho", "US"],
    ["209", "PST", "California", "US"],
    ["210", "CST", "Texas", "US"],
    ["212", "EST", "New York", "US"],
    ["213", "PST", "California", "US"],
    ["214", "CST", "Texas", "US"],
    ["215", "EST", "Pennsylvania", "US"],
    ["216", "EST", "Ohio", "US"],
    ["217", "CST", "Illinois", "US"],
    ["218", "CST", "Minnesota", "US"],
    ["219", "*EST, CST", "Indiana", "US"],
    ["220", "EST", "Ohio", "US"],
    ["223", "EST", "Pennsylvania", "US"],
    ["224", "CST", "Illinois", "US"],
    ["225", "CST", "Louisiana", "US"],
    ["226", "EST", "Ontario", "CA"],
    ["228", "CST", "Mississippi", "US"],
    ["229", "EST", "Georgia", "US"],
    ["231", "EST", "Michigan", "US"],
    ["234", "EST", "Ohio", "US"],
    ["236", "PST", "British Columbia", "CA"],
    ["239", "EST", "Florida", "US"],
    ["240", "EST", "Maryland", "US"],
    ["242", "EST", "The Bahamas"],
    ["246", "AST", "Barbados"],
    ["248", "EST", "Michigan", "US"],
    ["249", "EST", "Ontario", "CA"],
    ["250", "PST", "British Columbia", "CA"],
    ["251", "CST", "Alabama", "US"],
    ["252", "EST", "North Carolina", "US"],
    ["253", "PST", "Washington", "US"],
    ["254", "CST", "Texas", "US"],
    ["256", "CST", "Alabama", "US"],
    ["260", "EST", "Indiana", "US"],
    ["262", "CST", "Wisconsin", "US"],
    ["264", "AST", "Anguilla"],
    ["267", "EST", "Pennsylvania", "US"],
    ["268", "AST", "Antigua and Barbuda"],
    ["269", "EST", "Michigan", "US"],
    ["270", "*EST, CST", "Kentucky", "US"],
    ["272", "EST", "Pennsylvania", "US"],
    ["276", "EST", "Virginia", "US"],
    ["279", "PST", "California", "US"],
    ["281", "CST", "Texas", "US"],
    ["284", "AST", "British Virgin Islands"],
    ["289", "EST", "Ontario", "CA"],
    ["301", "EST", "Maryland", "US"],
    ["302", "EST", "Delaware", "US"],
    ["303", "MST", "Colorado", "US"],
    ["304", "EST", "West Virginia", "US"],
    ["305", "EST", "Florida", "US"],
    ["306", "CST", "Saskatchewan", "CA"],
    ["307", "MST", "Wyoming", "US"],
    ["308", "*CST, MST", "Nebraska", "US"],
    ["309", "CST", "Illinois", "US"],
    ["310", "PST", "California", "US"],
    ["312", "CST", "Illinois", "US"],
    ["313", "EST", "Michigan", "US"],
    ["314", "CST", "Missouri", "US"],
    ["315", "EST", "New York", "US"],
    ["316", "CST", "Kansas", "US"],
    ["317", "EST", "Indiana", "US"],
    ["318", "CST", "Louisiana", "US"],
    ["319", "CST", "Iowa", "US"],
    ["320", "CST", "Minnesota", "US"],
    ["321", "EST", "Florida", "US"],
    ["323", "PST", "California", "US"],
    ["325", "CST", "Texas", "US"],
    ["330", "EST", "Ohio", "US"],
    ["331", "CST", "Illinois", "US"],
    ["332", "EST", "New York", "US"],
    ["334", "CST", "Alabama", "US"],
    ["336", "EST", "North Carolina", "US"],
    ["337", "CST", "Louisiana", "US"],
    ["339", "EST", "Massachusetts", "US"],
    ["340", "AST", "U.S. Virgin Islands"],
    ["343", "EST", "Ontario", "CA"],
    ["345", "EST", "Cayman Islands"],
    ["346", "CST", "Texas", "US"],
    ["347", "EST", "New York", "US"],
    ["351", "EST", "Massachusetts", "US"],
    ["352", "EST", "Florida", "US"],
    ["360", "PST", "Washington", "US"],
    ["361", "CST", "Texas", "US"],
    ["364", "*EST, CST", "Kentucky", "US"],
    ["365", "EST", "Ontario", "CA"],
    ["367", "EST", "Quebec", "CA"],
    ["380", "EST", "Ohio", "US"],
    ["385", "MST", "Utah", "US"],
    ["386", "EST", "Florida", "US"],
    ["401", "EST", "Rhode Island", "US"],
    ["402", "CST", "Nebraska", "US"],
    ["403", "MST", "Alberta", "CA"],
    ["404", "EST", "Georgia", "US"],
    ["405", "CST", "Oklahoma", "US"],
    ["406", "MST", "Montana", "US"],
    ["407", "EST", "Florida", "US"],
    ["408", "PST", "California", "US"],
    ["409", "CST", "Texas", "US"],
    ["410", "EST", "Maryland", "US"],
    ["412", "EST", "Pennsylvania", "US"],
    ["413", "EST", "Massachusetts", "US"],
    ["414", "CST", "Wisconsin", "US"],
    ["415", "PST", "California", "US"],
    ["416", "EST", "Ontario", "CA"],
    ["417", "CST", "Missouri", "US"],
    ["418", "EST", "Quebec", "CA"],
    ["419", "EST", "Ohio", "US"],
    ["423", "*EST, CST", "Tennessee", "US"],
    ["424", "PST", "California", "US"],
    ["425", "PST", "Washington", "US"],
    ["430", "CST", "Texas", "US"],
    ["431", "Manitoba", "CA"],
    ["432", "CST", "Texas", "US"],
    ["434", "EST", "Virginia", "US"],
    ["435", "MST", "Utah", "US"],
    ["437", "EST", "Ontario", "CA"],
    ["438", "EST", "Quebec", "CA"],
    ["440", "EST", "Ohio", "US"],
    ["441", "AST", "Bermuda"],
    ["442", "PST", "California", "US"],
    ["443", "EST", "Maryland", "US"],
    ["445", "EST", "Pennsylvania", "US"],
    ["450", "EST", "Quebec", "CA"],
    ["456", "EST", "XX"],
    ["458", "MST, PST", "Oregon", "US"],
    ["463", "EST", "Indiana", "US"],
    ["469", "CST", "Texas", "US"],
    ["470", "EST", "Georgia", "US"],
    ["473", "AST", "Grenada"],
    ["475", "EST", "Connecticut", "US"],
    ["478", "EST", "Georgia", "US"],
    ["479", "CST", "Arkansas", "US"],
    ["480", "MST", "Arizona", "US"],
    ["484", "EST", "Pennsylvania", "US"],
    ["500", "EST", "XX"],
    ["501", "CST", "Arkansas", "US"],
    ["502", "EST", "Kentucky", "US"],
    ["503", "PST", "Oregon", "US"],
    ["504", "CST", "Louisiana", "US"],
    ["505", "MST", "New Mexico", "US"],
    ["506", "AST", "New Brunswick", "CA"],
    ["507", "CST", "Minnesota", "US"],
    ["508", "EST", "Massachusetts", "US"],
    ["509", "PST", "Washington", "US"],
    ["510", "PST", "California", "US"],
    ["512", "CST", "Texas", "US"],
    ["513", "EST", "Ohio", "US"],
    ["514", "EST", "Quebec", "CA"],
    ["515", "CST", "Iowa", "US"],
    ["516", "EST", "New York", "US"],
    ["517", "EST", "Michigan", "US"],
    ["518", "EST", "New York", "US"],
    ["519", "EST", "Ontario", "CA"],
    ["520", "MST", "Arizona", "US"],
    ["521", "EST", "XX"],
    ["522", "EST", "XX"],
    ["530", "PST", "California", "US"],
    ["531", "CST", "Nebraska", "US"],
    ["533", "EST", "XX"],
    ["534", "CST", "Wisconsin", "US"],
    ["539", "CST", "Oklahoma", "US"],
    ["540", "EST", "Virginia", "US"],
    ["541", "*MST, PST", "Oregon", "US"],
    ["544", "EST", "XX"],
    ["548", "EST", "Ontario", "CA"],
    ["551", "EST", "New Jersey", "US"],
    ["559", "PST", "California", "US"],
    ["561", "EST", "Florida", "US"],
    ["562", "PST", "California", "US"],
    ["563", "CST", "Iowa", "US"],
    ["564", "PST", "Washington", "US"],
    ["566", "EST", "XX"],
    ["567", "EST", "Ohio", "US"],
    ["570", "EST", "Pennsylvania", "US"],
    ["571", "EST", "Virginia", "US"],
    ["573", "CST", "Missouri", "US"],
    ["574", "*EST, CST", "Indiana", "US"],
    ["575", "MST", "New Mexico", "US"],
    ["577", "EST", "XX"],
    ["579", "EST", "Quebec", "CA"],
    ["580", "CST", "Oklahoma", "US"],
    ["581", "EST", "Quebec", "CA"],
    ["585", "EST", "New York", "US"],
    ["586", "EST", "Michigan", "US"],
    ["587", "MST", "Alberta", "CA"],
    ["588", "EST", "XX"],
    ["600", "EST", "CA"],
    ["601", "CST", "Mississippi", "US"],
    ["602", "MST", "Arizona", "US"],
    ["603", "EST", "New Hampshire", "US"],
    ["604", "PST", "British Columbia", "CA"],
    ["605", "*CST, MST", "South Dakota", "US"],
    ["606", "*EST, CST", "Kentucky", "US"],
    ["607", "EST", "New York", "US"],
    ["608", "CST", "Wisconsin", "US"],
    ["609", "EST", "New Jersey", "US"],
    ["610", "EST", "Pennsylvania", "US"],
    ["612", "CST", "Minnesota", "US"],
    ["613", "EST", "Ontario", "CA"],
    ["614", "EST", "Ohio", "US"],
    ["615", "CST", "Tennessee", "US"],
    ["616", "EST", "Michigan", "US"],
    ["617", "EST", "Massachusetts", "US"],
    ["618", "CST", "Illinois", "US"],
    ["619", "PST", "California", "US"],
    ["620", "*CST, MST", "Kansas", "US"],
    ["622", "EST", "CA"],
    ["623", "MST", "Arizona", "US"],
    ["626", "PST", "California", "US"],
    ["628", "PST", "California", "US"],
    ["629", "CST", "Tennessee", "US"],
    ["630", "CST", "Illinois", "US"],
    ["631", "EST", "New York", "US"],
    ["636", "CST", "Missouri", "US"],
    ["639", "CST", "Saskatchewan", "CA"],
    ["640", "EST", "New Jersey", "US"],
    ["641", "CST", "Iowa", "US"],
    ["646", "EST", "New York", "US"],
    ["647", "EST", "Ontario", "CA"],
    ["649", "EST", "Turks and Caicos Islands"],
    ["650", "PST", "California", "US"],
    ["651", "CST", "Minnesota", "US"],
    ["657", "PST", "California", "US"],
    ["660", "CST", "Missouri", "US"],
    ["661", "PST", "California", "US"],
    ["662", "CST", "Mississippi", "US"],
    ["664", "AST", "Montserrat"],
    ["667", "EST", "Maryland", "US"],
    ["669", "PST", "California", "US"],
    ["670", "Northern Marianas Islands"],
    ["671", "Guam"],
    ["678", "EST", "Georgia", "US"],
    ["680", "EST", "New York", "US"],
    ["681", "EST", "West Virginia", "US"],
    ["682", "CST", "Texas", "US"],
    ["684", "American Samoa"],
    ["700", "EST", "XX"],
    ["701", "*CST, MST", "North Dakota", "US"],
    ["702", "PST", "Nevada", "US"],
    ["703", "EST", "Virginia", "US"],
    ["704", "EST", "North Carolina", "US"],
    ["705", "EST", "Ontario", "CA"],
    ["706", "EST", "Georgia", "US"],
    ["707", "PST", "California", "US"],
    ["708", "CST", "Illinois", "US"],
    ["709", "NST, AST", "Newfoundland and Labrador", "CA"],
    ["710", "EST", "US"],
    ["712", "CST", "Iowa", "US"],
    ["713", "CST", "Texas", "US"],
    ["714", "PST", "California", "US"],
    ["715", "CST", "Wisconsin", "US"],
    ["716", "EST", "New York", "US"],
    ["717", "EST", "Pennsylvania", "US"],
    ["718", "EST", "New York", "US"],
    ["719", "MST", "Colorado", "US"],
    ["720", "MST", "Colorado", "US"],
    ["721", "AST", "Sint Maarten"],
    ["724", "EST", "Pennsylvania", "US"],
    ["725", "PST", "Nevada", "US"],
    ["726", "CST", "Texas", "US"],
    ["727", "EST", "Florida", "US"],
    ["731", "CST", "Tennessee", "US"],
    ["732", "EST", "New Jersey", "US"],
    ["734", "EST", "Michigan", "US"],
    ["737", "CST", "Texas", "US"],
    ["740", "EST", "Ohio", "US"],
    ["743", "EST", "North Carolina", "US"],
    ["747", "PST", "California", "US"],
    ["754", "EST", "Florida", "US"],
    ["757", "EST", "Virginia", "US"],
    ["758", "AST", "Saint Lucia"],
    ["760", "PST", "California", "US"],
    ["762", "EST", "Georgia", "US"],
    ["763", "CST", "Minnesota", "US"],
    ["765", "EST", "Indiana", "US"],
    ["767", "AST", "Dominica"],
    ["769", "CST", "Mississippi", "US"],
    ["770", "EST", "Georgia", "US"],
    ["772", "EST", "Florida", "US"],
    ["773", "CST", "Illinois", "US"],
    ["774", "EST", "Massachusetts", "US"],
    ["775", "PST", "Nevada", "US"],
    ["778", "PST", "British Columbia", "CA"],
    ["779", "CST", "Illinois", "US"],
    ["780", "MST", "Alberta", "CA"],
    ["781", "EST", "Massachusetts", "US"],
    ["782", "AST", "Nova Scotia, Prince Edward Island", "CA"],
    ["784", "AST", "Saint Vincent and the Grenadines"],
    ["785", "*CST, MST", "Kansas", "US"],
    ["786", "EST", "Florida", "US"],
    ["787", "AST", "Puerto Rico"],
    ["800", "EST", "XX"],
    ["801", "MST", "Utah", "US"],
    ["802", "EST", "Vermont", "US"],
    ["803", "EST", "South Carolina", "US"],
    ["804", "EST", "Virginia", "US"],
    ["805", "PST", "California", "US"],
    ["806", "CST", "Texas", "US"],
    ["807", "*EST, CST", "Ontario", "CA"],
    ["808", "(UTC-10)", "Hawaii", "US"],
    ["809", "EST", "Dominican Republic"],
    ["810", "EST", "Michigan", "US"],
    ["812", "*EST, CST", "Indiana", "US"],
    ["813", "EST", "Florida", "US"],
    ["814", "EST", "Pennsylvania", "US"],
    ["815", "CST", "Illinois", "US"],
    ["816", "CST", "Missouri", "US"],
    ["817", "CST", "Texas", "US"],
    ["818", "PST", "California", "US"],
    ["819", "EST", "Quebec", "CA"],
    ["820", "PST", "California", "US"],
    ["825", "MST", "Alberta", "CA"],
    ["828", "EST", "North Carolina", "US"],
    ["829", "EST", "Dominican Republic"],
    ["830", "CST", "Texas", "US"],
    ["831", "PST", "California", "US"],
    ["832", "CST", "Texas", "US"],
    ["833", "EST", "XX"],
    ["838", "EST", "New York", "US"],
    ["843", "EST", "South Carolina", "US"],
    ["844", "EST", "XX"],
    ["845", "EST", "New York", "US"],
    ["847", "CST", "Illinois", "US"],
    ["848", "EST", "New Jersey", "US"],
    ["849", "EST", "Dominican Republic"],
    ["850", "*EST, CST", "Florida", "US"],
    ["854", "EST", "South Carolina", "US"],
    ["855", "EST", "XX"],
    ["856", "EST", "New Jersey", "US"],
    ["857", "EST", "Massachusetts", "US"],
    ["858", "PST", "California", "US"],
    ["859", "EST", "Kentucky", "US"],
    ["860", "EST", "Connecticut", "US"],
    ["862", "EST", "New Jersey", "US"],
    ["863", "EST", "Florida", "US"],
    ["864", "EST", "South Carolina", "US"],
    ["865", "EST", "Tennessee", "US"],
    ["866", "EST"],
    ["867", "*CST, MST, PST", "Yukon, Northwest Territories, and Nunavut", "CA"],
    ["868", "AST", "Trinidad and Tobago"],
    ["869", "AST", "Saint Kitts and Nevis"],
    ["870", "CST", "Arkansas", "US"],
    ["872", "CST", "Illinois", "US"],
    ["873", "EST", "Quebec", "CA"],
    ["876", "EST", "Jamaica"],
    ["877", "EST", "XX"],
    ["878", "EST", "Pennsylvania", "US"],
    ["888", "EST", "XX"],
    ["900", "EST", "XX"],
    ["901", "CST", "Tennessee", "US"],
    ["902", "AST", "Nova Scotia, Prince Edward Island", "CA"],
    ["903", "CST", "Texas", "US"],
    ["904", "EST", "Florida", "US"],
    ["905", "EST", "Ontario", "CA"],
    ["906", "*EST, CST", "Michigan", "US"],
    ["907", "(UTC-9)", "Alaska", "US"],
    ["908", "EST", "New Jersey", "US"],
    ["909", "PST", "California", "US"],
    ["910", "EST", "North Carolina", "US"],
    ["912", "EST", "Georgia", "US"],
    ["913", "CST", "Kansas", "US"],
    ["914", "EST", "New York", "US"],
    ["915", "*CST, MST", "Texas", "US"],
    ["916", "PST", "California", "US"],
    ["917", "EST", "New York", "US"],
    ["918", "CST", "Oklahoma", "US"],
    ["919", "EST", "North Carolina", "US"],
    ["920", "CST", "Wisconsin", "US"],
    ["925", "PST", "California", "US"],
    ["928", "MST", "Arizona", "US"],
    ["929", "EST", "New York", "US"],
    ["930", "EST", "Indiana", "US"],
    ["931", "EST, CST", "Tennessee", "US"],
    ["934", "EST", "New York", "US"],
    ["936", "CST", "Texas", "US"],
    ["937", "EST", "Ohio", "US"],
    ["938", "CST", "Alabama", "US"],
    ["939", "AST", "Puerto Rico"],
    ["940", "CST", "Texas", "US"],
    ["941", "EST", "Florida", "US"],
    ["947", "EST", "Michigan", "US"],
    ["949", "PST", "California", "US"],
    ["951", "PST", "California", "US"],
    ["952", "CST", "Minnesota", "US"],
    ["954", "EST", "Florida", "US"],
    ["956", "CST", "Texas", "US"],
    ["959", "EST", "Connecticut", "US"],
    ["970", "MST", "Colorado", "US"],
    ["971", "PST", "Oregon", "US"],
    ["972", "CST", "Texas", "US"],
    ["973", "EST", "New Jersey", "US"],
    ["978", "EST", "Massachusetts", "US"],
    ["979", "CST", "Texas", "US"],
    ["980", "EST", "North Carolina", "US"],
    ["984", "EST", "North Carolina", "US"],
    ["985", "CST", "Louisiana", "US"],
    ["986", "PST", "Idaho", "US"],
    ["989", "EST", "Michigan", "US"]
]
